### ISSUE TITLE
Feature request: Add Pitch to midi learn

### ISSUE THREAD

**Issue by mark-orion** [hisschemoller/JS-EPG#5]
This is an awesome piece of software. Thanks you !
Would it be possible to add "Pitch" to the MIDI learn functionality? On one hand I do not have the MIDI note numbers in mind and on the other it can be fiddly to set the correct pitch. So my suggestion: Enable MIDI learn, click on "Pitch" of the processor and then send a Note On message by pressing the key you want on your MIDI keyboard - done.

**Comment by hisschemoller** [comment]
Thanks! MIDI channel, pitch and velocity can be controlled by external MIDI in the new release 2.2. But only with MIDI CCs in a useful way. Note On message are mostly useful as a switch to select something, like the new snapshots. Because one pitch is selected to be assigned to a task. I guess you suggest to have the whole range of pitches in a channel select the pitch of a processor? That is unfortunately not possible.

**Comment by hisschemoller** [comment]
This was added in version 2.2
